=== chengjf0526/nutzlib/XmlIocLoader_v1/src/nutz.ioc-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


	<xs:element name="nutzconfig" type="t_nutzconfig"></xs:element>

	<xs:attribute name="id" type="xs:string"></xs:attribute>

	<xs:attribute name="type" type="xs:string"></xs:attribute>

	<xs:attribute name="value" type="xs:string"></xs:attribute>

	<xs:attribute name="name" type="xs:string"></xs:attribute>


	<xs:complexType name="t_nutzconfig">
		<xs:sequence>
			<xs:element name="ioc" type="t_ioc" maxOccurs="1" minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="t_ioc">
		<xs:sequence>
			<xs:element name="bean" type="t_bean" maxOccurs="unbounded" minOccurs="1"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="t_bean">
		<xs:sequence>
			<xs:element name="args" type="t_args" maxOccurs="1"
				minOccurs="0">
			</xs:element>
			<xs:element name="fields" type="t_fields" maxOccurs="1"
				minOccurs="0">
			</xs:element>
			<xs:element name="events" type="t_events" maxOccurs="1"
				minOccurs="0">
			</xs:element>
		</xs:sequence>
		<xs:attribute ref="id" use="required"></xs:attribute>
		<xs:attribute ref="type"></xs:attribute>

		<xs:attribute ref="scope"></xs:attribute>
		<xs:attribute ref="parent"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="t_args">
		<xs:sequence>
			<xs:element name="arg" type="t_arg" maxOccurs="unbounded" minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="t_arg">
		<xs:attribute ref="type"></xs:attribute>
		<xs:attribute ref="value" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="t_events">
		<xs:sequence>
			<xs:element name="create" type="t_create" maxOccurs="1" minOccurs="0"></xs:element>
				<xs:element name="depose" type="t_depose" maxOccurs="1" minOccurs="0"></xs:element>
					<xs:element name="fetch" type="t_fetch" maxOccurs="1" minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>
    
	<xs:complexType name="t_fields">
		<xs:sequence>
			<xs:element name="field" type="t_field" maxOccurs="unbounded" minOccurs="1"></xs:element>
		</xs:sequence>
	</xs:complexType>
    



	<xs:attribute name="scope" type="xs:string"></xs:attribute>

	<xs:complexType name="t_create">
		<xs:attribute ref="value" use="required"></xs:attribute>
	</xs:complexType>
    
	<xs:complexType name="t_depose">
		<xs:attribute ref="value" use="required"></xs:attribute>
	</xs:complexType>
    
	<xs:complexType name="t_fetch">
		<xs:attribute ref="value" use="required"></xs:attribute>
	</xs:complexType>


	<xs:complexType name="t_field">
		<xs:attribute ref="name" use="required"></xs:attribute>
		<xs:attribute ref="type"></xs:attribute>
		<xs:attribute ref="value" use="required"></xs:attribute>
	</xs:complexType>

    <xs:attribute name="parent" type="xs:string"></xs:attribute>
</xs:schema>

=== chengjf0526/nutzlib/XmlIocLoader_v1/src/simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<nutzconfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="nutz.ioc-1.0.xsd">
	<ioc>
		<bean id="myBean" type="java.lang.Object">
			<args>
				<arg type="refer" value="sb"></arg>
			</args>
			<fields>
				<field name="Field2" type="java.lang.Long" value="10"></field>
			</fields>
			<events>
				<create value="create"></create>
				<depose value="depose"></depose>
				<fetch value="fetch"></fetch>
			</events>
		</bean>
		<bean id="sb" type="java.lang.Object"/>
		<bean id="fox" />
		<bean id="nutz" parent="fox">
		</bean>
		
		<bean id="op" type="java.lang.String">
			<args>
				<arg value="Wendal"/>
			</args>
		</bean>
		<bean id="op2" parent="op">
			<fields>
				<field name="xx" value="yy"/>
			</fields>
		</bean>
		
		<bean id="op3" parent="op2">
			<events>
				<depose value="depose"/>
			</events>
		</bean>
		
		<bean id="op4" parent="op3"></bean>
		
		<bean id="op5" parent="op2">
			<events>
				<create value="ct"/>
			</events>
		</bean>
		
		<bean id="sb2">
			<events>
				<create value="toString"/>
			</events>
		</bean>
		
		<!-- 循环依赖 -->
<!--		<bean id="p1" parent="p2"></bean>-->
<!--		<bean id="p2" parent="p1"></bean>-->
		<!-- 依赖自身 -->
<!--		<bean id="p3" parent="p3"></bean>-->
	</ioc>
</nutzconfig>
